server:
  port: 8082
spring:
  application:
    name: ms-client-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/ms_client
    username: root
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost