server:
  port: 8085
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: ms-catalog-service
          uri: lb://ms-catalog-service
          predicates:
            - Path=/category/**
